# Generated by Django 3.1.2 on 2020-10-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConpanyMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.IntegerField(verbose_name='设备名称')),
                ('buy_date', models.DateField(verbose_name='购置时间')),
                ('buy_name', models.CharField(max_length=100, verbose_name='购置人')),
                ('device_type', models.CharField(max_length=100, verbose_name='设备型号')),
                ('device_number', models.DateField(max_length=100, verbose_name='购置数量')),
                ('device_price', models.CharField(max_length=200, verbose_name='购置单价')),
            ],
            options={
                'verbose_name': '公司资产管理',
                'verbose_name_plural': '公司资产管理',
            },
        ),
    ]
