# Generated by Django 3.1.2 on 2020-10-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conpanymoney',
            name='device_number',
            field=models.CharField(max_length=100, verbose_name='购置数量'),
        ),
    ]
