# Generated by Django 3.1.2 on 2020-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20201029_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conpanymoney',
            name='device_name',
            field=models.CharField(max_length=100, verbose_name='设备名称'),
        ),
    ]
