# Generated by Django 3.1.2 on 2020-10-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='年份')),
                ('thing_name', models.CharField(max_length=16, verbose_name='销售产品')),
                ('leader_name', models.CharField(max_length=100, verbose_name='负责人')),
                ('quarter_first', models.CharField(max_length=200, verbose_name='第一季度销售情况')),
                ('quarter_second', models.CharField(max_length=200, verbose_name='第二季度销售情况')),
                ('quarter_third', models.CharField(max_length=200, verbose_name='第三季度销售情况')),
                ('quarter_forth', models.CharField(max_length=200, verbose_name='第四季度销售情况')),
            ],
            options={
                'verbose_name': '建策销售情况',
                'verbose_name_plural': '建策销售情况',
            },
        ),
    ]
