# Generated by Django 3.1.2 on 2020-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectManager_name', models.CharField(max_length=16, verbose_name='项目名称')),
                ('projectManager_time', models.DateField(verbose_name='项目时间')),
                ('projectMoney_name', models.CharField(max_length=100, verbose_name='项目出资方')),
                ('Project_leader', models.CharField(max_length=200, verbose_name='项目负责人')),
                ('Project_rate', models.CharField(max_length=200, verbose_name='项目完成进度')),
            ],
            options={
                'verbose_name': '建策项目管理',
                'verbose_name_plural': '建策项目管理',
            },
        ),
    ]
