# Generated by Django 3.1.2 on 2020-10-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PManager',
            new_name='PJManager',
        ),
    ]
