# Generated by Django 3.1.2 on 2020-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0002_auto_20201029_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjmanager',
            name='projectManager_name',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
    ]
