# Generated by Django 3.1.2 on 2020-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainjob',
            name='train_school',
            field=models.CharField(max_length=100, verbose_name='实训学校'),
        ),
    ]
