# Generated by Django 3.1.2 on 2020-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcmeeting',
            name='meeting_name',
            field=models.CharField(max_length=16, verbose_name='会议主题'),
        ),
    ]
