# Generated by Django 3.1.2 on 2020-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20201029_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jcmeeting',
            name='meeting_name',
            field=models.CharField(max_length=100, verbose_name='会议主题'),
        ),
    ]
