# Generated by Django 3.1.2 on 2020-10-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_name', models.IntegerField(verbose_name='推广产品')),
                ('extension_leader', models.CharField(max_length=100, verbose_name='负责人')),
                ('extension_target', models.CharField(max_length=100, verbose_name='受众目标')),
                ('start_time', models.DateField(verbose_name='开始推广时间')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='结束推广时间')),
                ('extension_effect', models.CharField(max_length=200, verbose_name='推广效果')),
            ],
            options={
                'verbose_name': '建策市场推广',
                'verbose_name_plural': '建策市场推广',
            },
        ),
    ]
