# Generated by Django 3.1.2 on 2020-10-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=16)),
                ('school_name', models.CharField(max_length=100)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField(blank=True)),
                ('company_name', models.CharField(max_length=200)),
                ('job_name', models.CharField(max_length=80)),
            ],
        ),
    ]
