# Generated by Django 3.1.2 on 2020-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentjob',
            options={'verbose_name': '学生就业信息表', 'verbose_name_plural': '学生就业信息表'},
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='就职公司'),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='离职时间'),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='job_name',
            field=models.CharField(max_length=80, verbose_name='就职岗位'),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='school_name',
            field=models.CharField(max_length=100, verbose_name='学校名字'),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='start_time',
            field=models.DateField(verbose_name='就职时间'),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='student_id',
            field=models.IntegerField(verbose_name='学员编号'),
        ),
        migrations.AlterField(
            model_name='studentjob',
            name='student_name',
            field=models.CharField(max_length=16, verbose_name='学生姓名'),
        ),
    ]
